language: ruby
before_install:
  - gem install bundler
before_script:
  - bundle update
cache: bundler
rvm:
  - 2.0.0
  - 2.1.10
  - 2.2.5
  - 2.3.1
  - 2.4.0-preview2
script:
  - "bundle exec rake test"
bundler_args: --jobs 3 --retry 3
